djfirst/djfirst/urls.py
from django.contrib import admin
from django.urls import include, path



urlpatterns = [
    path('admin/', admin.site.urls),	
	path('myapp/', include('myapp.urls', namespace='myapp')),
]

djfirst/myapp/urls.py
app_name = 'myapp'
from django.urls import path
from myapp import views

urlpatterns = [  
	path('about/', views.about, name='about'),
	path('contact/', views.contact, name='contact'),
	path('', views.index, name='home'),
	path('<int:my_id>/', views.indexItem, name='homeItem'),
]

djfirst/myapp/models.py
from django.db import models

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.FloatField(max_length=20)
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name

djfirst/myapp/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Product

def index(request):
    products = Product.objects.all()
    context = {
        'products': products
    }
    return render(request, 'myapp/index.html', context)
def indexItem(request, my_id):
    product = Product.objects.get(id=my_id)
    context = {
        'product': product
    }
    return render(request, 'myapp/indexitem.html', context)
    

def about(request):
    return HttpResponse("About page")

def contact(request):
    return render(request, 'myapp/contact.html')

djfirst/myapp/templates/myapp/contact.html
<html>
	<head></head>
	<body>
		<h1>Contact page</h1>
	</body>
</html>

djfirst/myapp/templates/myapp/index.html
{% load static %}
<html>
	<head>
		<link rel="stylesheet" href="{% static 'myapp/styles.css' %}" />
	</head>
	<body class="bg-gray-200">
		<h1 class="text-4xl font-bold text-center">Index page</h1>
		<h2>
			{% for product in products %}
			<a
				href="{% url 'myapp:homeItem' product.id %}"
				class="hover:text-blue-500"
			>
				<h3>ID: {{ product.id }} | name: {{ product.name }}</h3>
			</a>

			<p>price: {{ product.price }}</p>
			<p>description: {{ product.description }}</p>
			{% endfor %}
		</h2>
	</body>
</html>

djfirst/myapp/templates/myapp/indexitem.html
{% load static %}
<html>
	<head>
		<link rel="stylesheet" href="{% static 'myapp/style.css' %}" />
	</head>
	<body>
		<h1>Index item page</h1>
		<h2>ID: {{ product.id }} | name: {{ product.name }}</h2>
		<p>price: {{ product.price }}</p>
		<p>description: {{ product.description }}</p>
	</body>
</html>